package com.yayanovel.entity;

public class Bookshelf {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelf.BOOKSHELF_ID
     *
     * @mbg.generated Sun Aug 07 21:18:28 CST 2022
     */
    private Long bookshelfId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelf.BOOKSHELF_UID
     *
     * @mbg.generated Sun Aug 07 21:18:28 CST 2022
     */
    private String bookshelfUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelf.NOVEL_UID
     *
     * @mbg.generated Sun Aug 07 21:18:28 CST 2022
     */
    private String novelUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelf.USER_EMAIL
     *
     * @mbg.generated Sun Aug 07 21:18:28 CST 2022
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelf.TEXT1
     *
     * @mbg.generated Sun Aug 07 21:18:28 CST 2022
     */
    private String text1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelf.TEXT2
     *
     * @mbg.generated Sun Aug 07 21:18:28 CST 2022
     */
    private String text2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelf.BOOKSHELF_ID
     *
     * @return the value of bookshelf.BOOKSHELF_ID
     *
     * @mbg.generated Sun Aug 07 21:18:28 CST 2022
     */
    public Long getBookshelfId() {
        return bookshelfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelf.BOOKSHELF_ID
     *
     * @param bookshelfId the value for bookshelf.BOOKSHELF_ID
     *
     * @mbg.generated Sun Aug 07 21:18:28 CST 2022
     */
    public void setBookshelfId(Long bookshelfId) {
        this.bookshelfId = bookshelfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelf.BOOKSHELF_UID
     *
     * @return the value of bookshelf.BOOKSHELF_UID
     *
     * @mbg.generated Sun Aug 07 21:18:28 CST 2022
     */
    public String getBookshelfUid() {
        return bookshelfUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelf.BOOKSHELF_UID
     *
     * @param bookshelfUid the value for bookshelf.BOOKSHELF_UID
     *
     * @mbg.generated Sun Aug 07 21:18:28 CST 2022
     */
    public void setBookshelfUid(String bookshelfUid) {
        this.bookshelfUid = bookshelfUid == null ? null : bookshelfUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelf.NOVEL_UID
     *
     * @return the value of bookshelf.NOVEL_UID
     *
     * @mbg.generated Sun Aug 07 21:18:28 CST 2022
     */
    public String getNovelUid() {
        return novelUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelf.NOVEL_UID
     *
     * @param novelUid the value for bookshelf.NOVEL_UID
     *
     * @mbg.generated Sun Aug 07 21:18:28 CST 2022
     */
    public void setNovelUid(String novelUid) {
        this.novelUid = novelUid == null ? null : novelUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelf.USER_EMAIL
     *
     * @return the value of bookshelf.USER_EMAIL
     *
     * @mbg.generated Sun Aug 07 21:18:28 CST 2022
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelf.USER_EMAIL
     *
     * @param userEmail the value for bookshelf.USER_EMAIL
     *
     * @mbg.generated Sun Aug 07 21:18:28 CST 2022
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelf.TEXT1
     *
     * @return the value of bookshelf.TEXT1
     *
     * @mbg.generated Sun Aug 07 21:18:28 CST 2022
     */
    public String getText1() {
        return text1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelf.TEXT1
     *
     * @param text1 the value for bookshelf.TEXT1
     *
     * @mbg.generated Sun Aug 07 21:18:28 CST 2022
     */
    public void setText1(String text1) {
        this.text1 = text1 == null ? null : text1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelf.TEXT2
     *
     * @return the value of bookshelf.TEXT2
     *
     * @mbg.generated Sun Aug 07 21:18:28 CST 2022
     */
    public String getText2() {
        return text2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelf.TEXT2
     *
     * @param text2 the value for bookshelf.TEXT2
     *
     * @mbg.generated Sun Aug 07 21:18:28 CST 2022
     */
    public void setText2(String text2) {
        this.text2 = text2 == null ? null : text2.trim();
    }
}