package com.yayanovel.entity;

public class Chapter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.CHAPTER_ID
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    private Long chapterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.CHAPTER_UID
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    private String chapterUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.CHAPTER_NAME
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    private String chapterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.NOVEL_UID
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    private String novelUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.PRE_UID
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    private String preUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.BACK_UID
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    private String backUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.CHAPTER_NUM
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    private Long chapterNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.CHAPTER_ADDR
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    private String chapterAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.TEXT1
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    private String text1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.TEXT2
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    private String text2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.CHAPTER_ID
     *
     * @return the value of chapter.CHAPTER_ID
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    public Long getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.CHAPTER_ID
     *
     * @param chapterId the value for chapter.CHAPTER_ID
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    public void setChapterId(Long chapterId) {
        this.chapterId = chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.CHAPTER_UID
     *
     * @return the value of chapter.CHAPTER_UID
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    public String getChapterUid() {
        return chapterUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.CHAPTER_UID
     *
     * @param chapterUid the value for chapter.CHAPTER_UID
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    public void setChapterUid(String chapterUid) {
        this.chapterUid = chapterUid == null ? null : chapterUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.CHAPTER_NAME
     *
     * @return the value of chapter.CHAPTER_NAME
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    public String getChapterName() {
        return chapterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.CHAPTER_NAME
     *
     * @param chapterName the value for chapter.CHAPTER_NAME
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    public void setChapterName(String chapterName) {
        this.chapterName = chapterName == null ? null : chapterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.NOVEL_UID
     *
     * @return the value of chapter.NOVEL_UID
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    public String getNovelUid() {
        return novelUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.NOVEL_UID
     *
     * @param novelUid the value for chapter.NOVEL_UID
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    public void setNovelUid(String novelUid) {
        this.novelUid = novelUid == null ? null : novelUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.PRE_UID
     *
     * @return the value of chapter.PRE_UID
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    public String getPreUid() {
        return preUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.PRE_UID
     *
     * @param preUid the value for chapter.PRE_UID
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    public void setPreUid(String preUid) {
        this.preUid = preUid == null ? null : preUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.BACK_UID
     *
     * @return the value of chapter.BACK_UID
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    public String getBackUid() {
        return backUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.BACK_UID
     *
     * @param backUid the value for chapter.BACK_UID
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    public void setBackUid(String backUid) {
        this.backUid = backUid == null ? null : backUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.CHAPTER_NUM
     *
     * @return the value of chapter.CHAPTER_NUM
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    public Long getChapterNum() {
        return chapterNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.CHAPTER_NUM
     *
     * @param chapterNum the value for chapter.CHAPTER_NUM
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    public void setChapterNum(Long chapterNum) {
        this.chapterNum = chapterNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.CHAPTER_ADDR
     *
     * @return the value of chapter.CHAPTER_ADDR
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    public String getChapterAddr() {
        return chapterAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.CHAPTER_ADDR
     *
     * @param chapterAddr the value for chapter.CHAPTER_ADDR
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    public void setChapterAddr(String chapterAddr) {
        this.chapterAddr = chapterAddr == null ? null : chapterAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.TEXT1
     *
     * @return the value of chapter.TEXT1
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    public String getText1() {
        return text1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.TEXT1
     *
     * @param text1 the value for chapter.TEXT1
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    public void setText1(String text1) {
        this.text1 = text1 == null ? null : text1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.TEXT2
     *
     * @return the value of chapter.TEXT2
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    public String getText2() {
        return text2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.TEXT2
     *
     * @param text2 the value for chapter.TEXT2
     *
     * @mbg.generated Sun Aug 29 22:57:30 CST 2021
     */
    public void setText2(String text2) {
        this.text2 = text2 == null ? null : text2.trim();
    }
}