package com.yayanovel.entity;

public class Collection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.COLLECTION_ID
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    private Long collectionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.COLLECTION_UID
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    private String collectionUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.USER_UID
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    private String userUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.NOVEL_NAME
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    private String novelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.CHAPTER_UID
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    private String chapterUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.CHAPTER_NAME
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    private String chapterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.TEXT1
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    private String text1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.TEXT2
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    private String text2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.COLLECTION_ID
     *
     * @return the value of collection.COLLECTION_ID
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    public Long getCollectionId() {
        return collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.COLLECTION_ID
     *
     * @param collectionId the value for collection.COLLECTION_ID
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    public void setCollectionId(Long collectionId) {
        this.collectionId = collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.COLLECTION_UID
     *
     * @return the value of collection.COLLECTION_UID
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    public String getCollectionUid() {
        return collectionUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.COLLECTION_UID
     *
     * @param collectionUid the value for collection.COLLECTION_UID
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    public void setCollectionUid(String collectionUid) {
        this.collectionUid = collectionUid == null ? null : collectionUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.USER_UID
     *
     * @return the value of collection.USER_UID
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    public String getUserUid() {
        return userUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.USER_UID
     *
     * @param userUid the value for collection.USER_UID
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    public void setUserUid(String userUid) {
        this.userUid = userUid == null ? null : userUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.NOVEL_NAME
     *
     * @return the value of collection.NOVEL_NAME
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    public String getNovelName() {
        return novelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.NOVEL_NAME
     *
     * @param novelName the value for collection.NOVEL_NAME
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    public void setNovelName(String novelName) {
        this.novelName = novelName == null ? null : novelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.CHAPTER_UID
     *
     * @return the value of collection.CHAPTER_UID
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    public String getChapterUid() {
        return chapterUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.CHAPTER_UID
     *
     * @param chapterUid the value for collection.CHAPTER_UID
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    public void setChapterUid(String chapterUid) {
        this.chapterUid = chapterUid == null ? null : chapterUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.CHAPTER_NAME
     *
     * @return the value of collection.CHAPTER_NAME
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    public String getChapterName() {
        return chapterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.CHAPTER_NAME
     *
     * @param chapterName the value for collection.CHAPTER_NAME
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    public void setChapterName(String chapterName) {
        this.chapterName = chapterName == null ? null : chapterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.TEXT1
     *
     * @return the value of collection.TEXT1
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    public String getText1() {
        return text1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.TEXT1
     *
     * @param text1 the value for collection.TEXT1
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    public void setText1(String text1) {
        this.text1 = text1 == null ? null : text1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.TEXT2
     *
     * @return the value of collection.TEXT2
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    public String getText2() {
        return text2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.TEXT2
     *
     * @param text2 the value for collection.TEXT2
     *
     * @mbg.generated Sun Aug 29 22:57:50 CST 2021
     */
    public void setText2(String text2) {
        this.text2 = text2 == null ? null : text2.trim();
    }
}