package com.yayanovel.entity;

import java.util.ArrayList;
import java.util.List;

public class CollectionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    public CollectionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCollectionIdIsNull() {
            addCriterion("COLLECTION_ID is null");
            return (Criteria) this;
        }

        public Criteria andCollectionIdIsNotNull() {
            addCriterion("COLLECTION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCollectionIdEqualTo(Long value) {
            addCriterion("COLLECTION_ID =", value, "collectionId");
            return (Criteria) this;
        }

        public Criteria andCollectionIdNotEqualTo(Long value) {
            addCriterion("COLLECTION_ID <>", value, "collectionId");
            return (Criteria) this;
        }

        public Criteria andCollectionIdGreaterThan(Long value) {
            addCriterion("COLLECTION_ID >", value, "collectionId");
            return (Criteria) this;
        }

        public Criteria andCollectionIdGreaterThanOrEqualTo(Long value) {
            addCriterion("COLLECTION_ID >=", value, "collectionId");
            return (Criteria) this;
        }

        public Criteria andCollectionIdLessThan(Long value) {
            addCriterion("COLLECTION_ID <", value, "collectionId");
            return (Criteria) this;
        }

        public Criteria andCollectionIdLessThanOrEqualTo(Long value) {
            addCriterion("COLLECTION_ID <=", value, "collectionId");
            return (Criteria) this;
        }

        public Criteria andCollectionIdIn(List<Long> values) {
            addCriterion("COLLECTION_ID in", values, "collectionId");
            return (Criteria) this;
        }

        public Criteria andCollectionIdNotIn(List<Long> values) {
            addCriterion("COLLECTION_ID not in", values, "collectionId");
            return (Criteria) this;
        }

        public Criteria andCollectionIdBetween(Long value1, Long value2) {
            addCriterion("COLLECTION_ID between", value1, value2, "collectionId");
            return (Criteria) this;
        }

        public Criteria andCollectionIdNotBetween(Long value1, Long value2) {
            addCriterion("COLLECTION_ID not between", value1, value2, "collectionId");
            return (Criteria) this;
        }

        public Criteria andCollectionUidIsNull() {
            addCriterion("COLLECTION_UID is null");
            return (Criteria) this;
        }

        public Criteria andCollectionUidIsNotNull() {
            addCriterion("COLLECTION_UID is not null");
            return (Criteria) this;
        }

        public Criteria andCollectionUidEqualTo(String value) {
            addCriterion("COLLECTION_UID =", value, "collectionUid");
            return (Criteria) this;
        }

        public Criteria andCollectionUidNotEqualTo(String value) {
            addCriterion("COLLECTION_UID <>", value, "collectionUid");
            return (Criteria) this;
        }

        public Criteria andCollectionUidGreaterThan(String value) {
            addCriterion("COLLECTION_UID >", value, "collectionUid");
            return (Criteria) this;
        }

        public Criteria andCollectionUidGreaterThanOrEqualTo(String value) {
            addCriterion("COLLECTION_UID >=", value, "collectionUid");
            return (Criteria) this;
        }

        public Criteria andCollectionUidLessThan(String value) {
            addCriterion("COLLECTION_UID <", value, "collectionUid");
            return (Criteria) this;
        }

        public Criteria andCollectionUidLessThanOrEqualTo(String value) {
            addCriterion("COLLECTION_UID <=", value, "collectionUid");
            return (Criteria) this;
        }

        public Criteria andCollectionUidLike(String value) {
            addCriterion("COLLECTION_UID like", value, "collectionUid");
            return (Criteria) this;
        }

        public Criteria andCollectionUidNotLike(String value) {
            addCriterion("COLLECTION_UID not like", value, "collectionUid");
            return (Criteria) this;
        }

        public Criteria andCollectionUidIn(List<String> values) {
            addCriterion("COLLECTION_UID in", values, "collectionUid");
            return (Criteria) this;
        }

        public Criteria andCollectionUidNotIn(List<String> values) {
            addCriterion("COLLECTION_UID not in", values, "collectionUid");
            return (Criteria) this;
        }

        public Criteria andCollectionUidBetween(String value1, String value2) {
            addCriterion("COLLECTION_UID between", value1, value2, "collectionUid");
            return (Criteria) this;
        }

        public Criteria andCollectionUidNotBetween(String value1, String value2) {
            addCriterion("COLLECTION_UID not between", value1, value2, "collectionUid");
            return (Criteria) this;
        }

        public Criteria andUserUidIsNull() {
            addCriterion("USER_UID is null");
            return (Criteria) this;
        }

        public Criteria andUserUidIsNotNull() {
            addCriterion("USER_UID is not null");
            return (Criteria) this;
        }

        public Criteria andUserUidEqualTo(String value) {
            addCriterion("USER_UID =", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotEqualTo(String value) {
            addCriterion("USER_UID <>", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidGreaterThan(String value) {
            addCriterion("USER_UID >", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidGreaterThanOrEqualTo(String value) {
            addCriterion("USER_UID >=", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidLessThan(String value) {
            addCriterion("USER_UID <", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidLessThanOrEqualTo(String value) {
            addCriterion("USER_UID <=", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidLike(String value) {
            addCriterion("USER_UID like", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotLike(String value) {
            addCriterion("USER_UID not like", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidIn(List<String> values) {
            addCriterion("USER_UID in", values, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotIn(List<String> values) {
            addCriterion("USER_UID not in", values, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidBetween(String value1, String value2) {
            addCriterion("USER_UID between", value1, value2, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotBetween(String value1, String value2) {
            addCriterion("USER_UID not between", value1, value2, "userUid");
            return (Criteria) this;
        }

        public Criteria andNovelNameIsNull() {
            addCriterion("NOVEL_NAME is null");
            return (Criteria) this;
        }

        public Criteria andNovelNameIsNotNull() {
            addCriterion("NOVEL_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNovelNameEqualTo(String value) {
            addCriterion("NOVEL_NAME =", value, "novelName");
            return (Criteria) this;
        }

        public Criteria andNovelNameNotEqualTo(String value) {
            addCriterion("NOVEL_NAME <>", value, "novelName");
            return (Criteria) this;
        }

        public Criteria andNovelNameGreaterThan(String value) {
            addCriterion("NOVEL_NAME >", value, "novelName");
            return (Criteria) this;
        }

        public Criteria andNovelNameGreaterThanOrEqualTo(String value) {
            addCriterion("NOVEL_NAME >=", value, "novelName");
            return (Criteria) this;
        }

        public Criteria andNovelNameLessThan(String value) {
            addCriterion("NOVEL_NAME <", value, "novelName");
            return (Criteria) this;
        }

        public Criteria andNovelNameLessThanOrEqualTo(String value) {
            addCriterion("NOVEL_NAME <=", value, "novelName");
            return (Criteria) this;
        }

        public Criteria andNovelNameLike(String value) {
            addCriterion("NOVEL_NAME like", value, "novelName");
            return (Criteria) this;
        }

        public Criteria andNovelNameNotLike(String value) {
            addCriterion("NOVEL_NAME not like", value, "novelName");
            return (Criteria) this;
        }

        public Criteria andNovelNameIn(List<String> values) {
            addCriterion("NOVEL_NAME in", values, "novelName");
            return (Criteria) this;
        }

        public Criteria andNovelNameNotIn(List<String> values) {
            addCriterion("NOVEL_NAME not in", values, "novelName");
            return (Criteria) this;
        }

        public Criteria andNovelNameBetween(String value1, String value2) {
            addCriterion("NOVEL_NAME between", value1, value2, "novelName");
            return (Criteria) this;
        }

        public Criteria andNovelNameNotBetween(String value1, String value2) {
            addCriterion("NOVEL_NAME not between", value1, value2, "novelName");
            return (Criteria) this;
        }

        public Criteria andNovelUidIsNull() {
            addCriterion("NOVEL_UID is null");
            return (Criteria) this;
        }

        public Criteria andNovelUidIsNotNull() {
            addCriterion("NOVEL_UID is not null");
            return (Criteria) this;
        }

        public Criteria andNovelUidEqualTo(String value) {
            addCriterion("NOVEL_UID =", value, "novelUid");
            return (Criteria) this;
        }

        public Criteria andNovelUidNotEqualTo(String value) {
            addCriterion("NOVEL_UID <>", value, "novelUid");
            return (Criteria) this;
        }

        public Criteria andNovelUidGreaterThan(String value) {
            addCriterion("NOVEL_UID >", value, "novelUid");
            return (Criteria) this;
        }

        public Criteria andNovelUidGreaterThanOrEqualTo(String value) {
            addCriterion("NOVEL_UID >=", value, "novelUid");
            return (Criteria) this;
        }

        public Criteria andNovelUidLessThan(String value) {
            addCriterion("NOVEL_UID <", value, "novelUid");
            return (Criteria) this;
        }

        public Criteria andNovelUidLessThanOrEqualTo(String value) {
            addCriterion("NOVEL_UID <=", value, "novelUid");
            return (Criteria) this;
        }

        public Criteria andNovelUidLike(String value) {
            addCriterion("NOVEL_UID like", value, "novelUid");
            return (Criteria) this;
        }

        public Criteria andNovelUidNotLike(String value) {
            addCriterion("NOVEL_UID not like", value, "novelUid");
            return (Criteria) this;
        }

        public Criteria andNovelUidIn(List<String> values) {
            addCriterion("NOVEL_UID in", values, "novelUid");
            return (Criteria) this;
        }

        public Criteria andNovelUidNotIn(List<String> values) {
            addCriterion("NOVEL_UID not in", values, "novelUid");
            return (Criteria) this;
        }

        public Criteria andNovelUidBetween(String value1, String value2) {
            addCriterion("NOVEL_UID between", value1, value2, "novelUid");
            return (Criteria) this;
        }

        public Criteria andNovelUidNotBetween(String value1, String value2) {
            addCriterion("NOVEL_UID not between", value1, value2, "novelUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidIsNull() {
            addCriterion("CHAPTER_UID is null");
            return (Criteria) this;
        }

        public Criteria andChapterUidIsNotNull() {
            addCriterion("CHAPTER_UID is not null");
            return (Criteria) this;
        }

        public Criteria andChapterUidEqualTo(String value) {
            addCriterion("CHAPTER_UID =", value, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidNotEqualTo(String value) {
            addCriterion("CHAPTER_UID <>", value, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidGreaterThan(String value) {
            addCriterion("CHAPTER_UID >", value, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidGreaterThanOrEqualTo(String value) {
            addCriterion("CHAPTER_UID >=", value, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidLessThan(String value) {
            addCriterion("CHAPTER_UID <", value, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidLessThanOrEqualTo(String value) {
            addCriterion("CHAPTER_UID <=", value, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidLike(String value) {
            addCriterion("CHAPTER_UID like", value, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidNotLike(String value) {
            addCriterion("CHAPTER_UID not like", value, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidIn(List<String> values) {
            addCriterion("CHAPTER_UID in", values, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidNotIn(List<String> values) {
            addCriterion("CHAPTER_UID not in", values, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidBetween(String value1, String value2) {
            addCriterion("CHAPTER_UID between", value1, value2, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidNotBetween(String value1, String value2) {
            addCriterion("CHAPTER_UID not between", value1, value2, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andChapterNameIsNull() {
            addCriterion("CHAPTER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andChapterNameIsNotNull() {
            addCriterion("CHAPTER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andChapterNameEqualTo(String value) {
            addCriterion("CHAPTER_NAME =", value, "chapterName");
            return (Criteria) this;
        }

        public Criteria andChapterNameNotEqualTo(String value) {
            addCriterion("CHAPTER_NAME <>", value, "chapterName");
            return (Criteria) this;
        }

        public Criteria andChapterNameGreaterThan(String value) {
            addCriterion("CHAPTER_NAME >", value, "chapterName");
            return (Criteria) this;
        }

        public Criteria andChapterNameGreaterThanOrEqualTo(String value) {
            addCriterion("CHAPTER_NAME >=", value, "chapterName");
            return (Criteria) this;
        }

        public Criteria andChapterNameLessThan(String value) {
            addCriterion("CHAPTER_NAME <", value, "chapterName");
            return (Criteria) this;
        }

        public Criteria andChapterNameLessThanOrEqualTo(String value) {
            addCriterion("CHAPTER_NAME <=", value, "chapterName");
            return (Criteria) this;
        }

        public Criteria andChapterNameLike(String value) {
            addCriterion("CHAPTER_NAME like", value, "chapterName");
            return (Criteria) this;
        }

        public Criteria andChapterNameNotLike(String value) {
            addCriterion("CHAPTER_NAME not like", value, "chapterName");
            return (Criteria) this;
        }

        public Criteria andChapterNameIn(List<String> values) {
            addCriterion("CHAPTER_NAME in", values, "chapterName");
            return (Criteria) this;
        }

        public Criteria andChapterNameNotIn(List<String> values) {
            addCriterion("CHAPTER_NAME not in", values, "chapterName");
            return (Criteria) this;
        }

        public Criteria andChapterNameBetween(String value1, String value2) {
            addCriterion("CHAPTER_NAME between", value1, value2, "chapterName");
            return (Criteria) this;
        }

        public Criteria andChapterNameNotBetween(String value1, String value2) {
            addCriterion("CHAPTER_NAME not between", value1, value2, "chapterName");
            return (Criteria) this;
        }

        public Criteria andText1IsNull() {
            addCriterion("TEXT1 is null");
            return (Criteria) this;
        }

        public Criteria andText1IsNotNull() {
            addCriterion("TEXT1 is not null");
            return (Criteria) this;
        }

        public Criteria andText1EqualTo(String value) {
            addCriterion("TEXT1 =", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1NotEqualTo(String value) {
            addCriterion("TEXT1 <>", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1GreaterThan(String value) {
            addCriterion("TEXT1 >", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1GreaterThanOrEqualTo(String value) {
            addCriterion("TEXT1 >=", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1LessThan(String value) {
            addCriterion("TEXT1 <", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1LessThanOrEqualTo(String value) {
            addCriterion("TEXT1 <=", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1Like(String value) {
            addCriterion("TEXT1 like", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1NotLike(String value) {
            addCriterion("TEXT1 not like", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1In(List<String> values) {
            addCriterion("TEXT1 in", values, "text1");
            return (Criteria) this;
        }

        public Criteria andText1NotIn(List<String> values) {
            addCriterion("TEXT1 not in", values, "text1");
            return (Criteria) this;
        }

        public Criteria andText1Between(String value1, String value2) {
            addCriterion("TEXT1 between", value1, value2, "text1");
            return (Criteria) this;
        }

        public Criteria andText1NotBetween(String value1, String value2) {
            addCriterion("TEXT1 not between", value1, value2, "text1");
            return (Criteria) this;
        }

        public Criteria andText2IsNull() {
            addCriterion("TEXT2 is null");
            return (Criteria) this;
        }

        public Criteria andText2IsNotNull() {
            addCriterion("TEXT2 is not null");
            return (Criteria) this;
        }

        public Criteria andText2EqualTo(String value) {
            addCriterion("TEXT2 =", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2NotEqualTo(String value) {
            addCriterion("TEXT2 <>", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2GreaterThan(String value) {
            addCriterion("TEXT2 >", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2GreaterThanOrEqualTo(String value) {
            addCriterion("TEXT2 >=", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2LessThan(String value) {
            addCriterion("TEXT2 <", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2LessThanOrEqualTo(String value) {
            addCriterion("TEXT2 <=", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2Like(String value) {
            addCriterion("TEXT2 like", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2NotLike(String value) {
            addCriterion("TEXT2 not like", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2In(List<String> values) {
            addCriterion("TEXT2 in", values, "text2");
            return (Criteria) this;
        }

        public Criteria andText2NotIn(List<String> values) {
            addCriterion("TEXT2 not in", values, "text2");
            return (Criteria) this;
        }

        public Criteria andText2Between(String value1, String value2) {
            addCriterion("TEXT2 between", value1, value2, "text2");
            return (Criteria) this;
        }

        public Criteria andText2NotBetween(String value1, String value2) {
            addCriterion("TEXT2 not between", value1, value2, "text2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table collection
     *
     * @mbg.generated do_not_delete_during_merge Thu Oct 07 10:04:31 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}