package com.yayanovel.entity;

import java.util.ArrayList;
import java.util.List;

public class NovelContentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public NovelContentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNovelContentIdIsNull() {
            addCriterion("NOVEL_CONTENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andNovelContentIdIsNotNull() {
            addCriterion("NOVEL_CONTENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andNovelContentIdEqualTo(Long value) {
            addCriterion("NOVEL_CONTENT_ID =", value, "novelContentId");
            return (Criteria) this;
        }

        public Criteria andNovelContentIdNotEqualTo(Long value) {
            addCriterion("NOVEL_CONTENT_ID <>", value, "novelContentId");
            return (Criteria) this;
        }

        public Criteria andNovelContentIdGreaterThan(Long value) {
            addCriterion("NOVEL_CONTENT_ID >", value, "novelContentId");
            return (Criteria) this;
        }

        public Criteria andNovelContentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("NOVEL_CONTENT_ID >=", value, "novelContentId");
            return (Criteria) this;
        }

        public Criteria andNovelContentIdLessThan(Long value) {
            addCriterion("NOVEL_CONTENT_ID <", value, "novelContentId");
            return (Criteria) this;
        }

        public Criteria andNovelContentIdLessThanOrEqualTo(Long value) {
            addCriterion("NOVEL_CONTENT_ID <=", value, "novelContentId");
            return (Criteria) this;
        }

        public Criteria andNovelContentIdIn(List<Long> values) {
            addCriterion("NOVEL_CONTENT_ID in", values, "novelContentId");
            return (Criteria) this;
        }

        public Criteria andNovelContentIdNotIn(List<Long> values) {
            addCriterion("NOVEL_CONTENT_ID not in", values, "novelContentId");
            return (Criteria) this;
        }

        public Criteria andNovelContentIdBetween(Long value1, Long value2) {
            addCriterion("NOVEL_CONTENT_ID between", value1, value2, "novelContentId");
            return (Criteria) this;
        }

        public Criteria andNovelContentIdNotBetween(Long value1, Long value2) {
            addCriterion("NOVEL_CONTENT_ID not between", value1, value2, "novelContentId");
            return (Criteria) this;
        }

        public Criteria andNovelContentUidIsNull() {
            addCriterion("NOVEL_CONTENT_UID is null");
            return (Criteria) this;
        }

        public Criteria andNovelContentUidIsNotNull() {
            addCriterion("NOVEL_CONTENT_UID is not null");
            return (Criteria) this;
        }

        public Criteria andNovelContentUidEqualTo(String value) {
            addCriterion("NOVEL_CONTENT_UID =", value, "novelContentUid");
            return (Criteria) this;
        }

        public Criteria andNovelContentUidNotEqualTo(String value) {
            addCriterion("NOVEL_CONTENT_UID <>", value, "novelContentUid");
            return (Criteria) this;
        }

        public Criteria andNovelContentUidGreaterThan(String value) {
            addCriterion("NOVEL_CONTENT_UID >", value, "novelContentUid");
            return (Criteria) this;
        }

        public Criteria andNovelContentUidGreaterThanOrEqualTo(String value) {
            addCriterion("NOVEL_CONTENT_UID >=", value, "novelContentUid");
            return (Criteria) this;
        }

        public Criteria andNovelContentUidLessThan(String value) {
            addCriterion("NOVEL_CONTENT_UID <", value, "novelContentUid");
            return (Criteria) this;
        }

        public Criteria andNovelContentUidLessThanOrEqualTo(String value) {
            addCriterion("NOVEL_CONTENT_UID <=", value, "novelContentUid");
            return (Criteria) this;
        }

        public Criteria andNovelContentUidLike(String value) {
            addCriterion("NOVEL_CONTENT_UID like", value, "novelContentUid");
            return (Criteria) this;
        }

        public Criteria andNovelContentUidNotLike(String value) {
            addCriterion("NOVEL_CONTENT_UID not like", value, "novelContentUid");
            return (Criteria) this;
        }

        public Criteria andNovelContentUidIn(List<String> values) {
            addCriterion("NOVEL_CONTENT_UID in", values, "novelContentUid");
            return (Criteria) this;
        }

        public Criteria andNovelContentUidNotIn(List<String> values) {
            addCriterion("NOVEL_CONTENT_UID not in", values, "novelContentUid");
            return (Criteria) this;
        }

        public Criteria andNovelContentUidBetween(String value1, String value2) {
            addCriterion("NOVEL_CONTENT_UID between", value1, value2, "novelContentUid");
            return (Criteria) this;
        }

        public Criteria andNovelContentUidNotBetween(String value1, String value2) {
            addCriterion("NOVEL_CONTENT_UID not between", value1, value2, "novelContentUid");
            return (Criteria) this;
        }

        public Criteria andNovelUidIsNull() {
            addCriterion("NOVEL_UID is null");
            return (Criteria) this;
        }

        public Criteria andNovelUidIsNotNull() {
            addCriterion("NOVEL_UID is not null");
            return (Criteria) this;
        }

        public Criteria andNovelUidEqualTo(String value) {
            addCriterion("NOVEL_UID =", value, "novelUid");
            return (Criteria) this;
        }

        public Criteria andNovelUidNotEqualTo(String value) {
            addCriterion("NOVEL_UID <>", value, "novelUid");
            return (Criteria) this;
        }

        public Criteria andNovelUidGreaterThan(String value) {
            addCriterion("NOVEL_UID >", value, "novelUid");
            return (Criteria) this;
        }

        public Criteria andNovelUidGreaterThanOrEqualTo(String value) {
            addCriterion("NOVEL_UID >=", value, "novelUid");
            return (Criteria) this;
        }

        public Criteria andNovelUidLessThan(String value) {
            addCriterion("NOVEL_UID <", value, "novelUid");
            return (Criteria) this;
        }

        public Criteria andNovelUidLessThanOrEqualTo(String value) {
            addCriterion("NOVEL_UID <=", value, "novelUid");
            return (Criteria) this;
        }

        public Criteria andNovelUidLike(String value) {
            addCriterion("NOVEL_UID like", value, "novelUid");
            return (Criteria) this;
        }

        public Criteria andNovelUidNotLike(String value) {
            addCriterion("NOVEL_UID not like", value, "novelUid");
            return (Criteria) this;
        }

        public Criteria andNovelUidIn(List<String> values) {
            addCriterion("NOVEL_UID in", values, "novelUid");
            return (Criteria) this;
        }

        public Criteria andNovelUidNotIn(List<String> values) {
            addCriterion("NOVEL_UID not in", values, "novelUid");
            return (Criteria) this;
        }

        public Criteria andNovelUidBetween(String value1, String value2) {
            addCriterion("NOVEL_UID between", value1, value2, "novelUid");
            return (Criteria) this;
        }

        public Criteria andNovelUidNotBetween(String value1, String value2) {
            addCriterion("NOVEL_UID not between", value1, value2, "novelUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidIsNull() {
            addCriterion("CHAPTER_UID is null");
            return (Criteria) this;
        }

        public Criteria andChapterUidIsNotNull() {
            addCriterion("CHAPTER_UID is not null");
            return (Criteria) this;
        }

        public Criteria andChapterUidEqualTo(String value) {
            addCriterion("CHAPTER_UID =", value, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidNotEqualTo(String value) {
            addCriterion("CHAPTER_UID <>", value, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidGreaterThan(String value) {
            addCriterion("CHAPTER_UID >", value, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidGreaterThanOrEqualTo(String value) {
            addCriterion("CHAPTER_UID >=", value, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidLessThan(String value) {
            addCriterion("CHAPTER_UID <", value, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidLessThanOrEqualTo(String value) {
            addCriterion("CHAPTER_UID <=", value, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidLike(String value) {
            addCriterion("CHAPTER_UID like", value, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidNotLike(String value) {
            addCriterion("CHAPTER_UID not like", value, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidIn(List<String> values) {
            addCriterion("CHAPTER_UID in", values, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidNotIn(List<String> values) {
            addCriterion("CHAPTER_UID not in", values, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidBetween(String value1, String value2) {
            addCriterion("CHAPTER_UID between", value1, value2, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andChapterUidNotBetween(String value1, String value2) {
            addCriterion("CHAPTER_UID not between", value1, value2, "chapterUid");
            return (Criteria) this;
        }

        public Criteria andNovelNameIsNull() {
            addCriterion("NOVEL_NAME is null");
            return (Criteria) this;
        }

        public Criteria andNovelNameIsNotNull() {
            addCriterion("NOVEL_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNovelNameEqualTo(String value) {
            addCriterion("NOVEL_NAME =", value, "novelName");
            return (Criteria) this;
        }

        public Criteria andNovelNameNotEqualTo(String value) {
            addCriterion("NOVEL_NAME <>", value, "novelName");
            return (Criteria) this;
        }

        public Criteria andNovelNameGreaterThan(String value) {
            addCriterion("NOVEL_NAME >", value, "novelName");
            return (Criteria) this;
        }

        public Criteria andNovelNameGreaterThanOrEqualTo(String value) {
            addCriterion("NOVEL_NAME >=", value, "novelName");
            return (Criteria) this;
        }

        public Criteria andNovelNameLessThan(String value) {
            addCriterion("NOVEL_NAME <", value, "novelName");
            return (Criteria) this;
        }

        public Criteria andNovelNameLessThanOrEqualTo(String value) {
            addCriterion("NOVEL_NAME <=", value, "novelName");
            return (Criteria) this;
        }

        public Criteria andNovelNameLike(String value) {
            addCriterion("NOVEL_NAME like", value, "novelName");
            return (Criteria) this;
        }

        public Criteria andNovelNameNotLike(String value) {
            addCriterion("NOVEL_NAME not like", value, "novelName");
            return (Criteria) this;
        }

        public Criteria andNovelNameIn(List<String> values) {
            addCriterion("NOVEL_NAME in", values, "novelName");
            return (Criteria) this;
        }

        public Criteria andNovelNameNotIn(List<String> values) {
            addCriterion("NOVEL_NAME not in", values, "novelName");
            return (Criteria) this;
        }

        public Criteria andNovelNameBetween(String value1, String value2) {
            addCriterion("NOVEL_NAME between", value1, value2, "novelName");
            return (Criteria) this;
        }

        public Criteria andNovelNameNotBetween(String value1, String value2) {
            addCriterion("NOVEL_NAME not between", value1, value2, "novelName");
            return (Criteria) this;
        }

        public Criteria andChapterNameIsNull() {
            addCriterion("CHAPTER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andChapterNameIsNotNull() {
            addCriterion("CHAPTER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andChapterNameEqualTo(String value) {
            addCriterion("CHAPTER_NAME =", value, "chapterName");
            return (Criteria) this;
        }

        public Criteria andChapterNameNotEqualTo(String value) {
            addCriterion("CHAPTER_NAME <>", value, "chapterName");
            return (Criteria) this;
        }

        public Criteria andChapterNameGreaterThan(String value) {
            addCriterion("CHAPTER_NAME >", value, "chapterName");
            return (Criteria) this;
        }

        public Criteria andChapterNameGreaterThanOrEqualTo(String value) {
            addCriterion("CHAPTER_NAME >=", value, "chapterName");
            return (Criteria) this;
        }

        public Criteria andChapterNameLessThan(String value) {
            addCriterion("CHAPTER_NAME <", value, "chapterName");
            return (Criteria) this;
        }

        public Criteria andChapterNameLessThanOrEqualTo(String value) {
            addCriterion("CHAPTER_NAME <=", value, "chapterName");
            return (Criteria) this;
        }

        public Criteria andChapterNameLike(String value) {
            addCriterion("CHAPTER_NAME like", value, "chapterName");
            return (Criteria) this;
        }

        public Criteria andChapterNameNotLike(String value) {
            addCriterion("CHAPTER_NAME not like", value, "chapterName");
            return (Criteria) this;
        }

        public Criteria andChapterNameIn(List<String> values) {
            addCriterion("CHAPTER_NAME in", values, "chapterName");
            return (Criteria) this;
        }

        public Criteria andChapterNameNotIn(List<String> values) {
            addCriterion("CHAPTER_NAME not in", values, "chapterName");
            return (Criteria) this;
        }

        public Criteria andChapterNameBetween(String value1, String value2) {
            addCriterion("CHAPTER_NAME between", value1, value2, "chapterName");
            return (Criteria) this;
        }

        public Criteria andChapterNameNotBetween(String value1, String value2) {
            addCriterion("CHAPTER_NAME not between", value1, value2, "chapterName");
            return (Criteria) this;
        }

        public Criteria andNovelContnetIsNull() {
            addCriterion("NOVEL_CONTNET is null");
            return (Criteria) this;
        }

        public Criteria andNovelContnetIsNotNull() {
            addCriterion("NOVEL_CONTNET is not null");
            return (Criteria) this;
        }

        public Criteria andNovelContnetEqualTo(String value) {
            addCriterion("NOVEL_CONTNET =", value, "novelContnet");
            return (Criteria) this;
        }

        public Criteria andNovelContnetNotEqualTo(String value) {
            addCriterion("NOVEL_CONTNET <>", value, "novelContnet");
            return (Criteria) this;
        }

        public Criteria andNovelContnetGreaterThan(String value) {
            addCriterion("NOVEL_CONTNET >", value, "novelContnet");
            return (Criteria) this;
        }

        public Criteria andNovelContnetGreaterThanOrEqualTo(String value) {
            addCriterion("NOVEL_CONTNET >=", value, "novelContnet");
            return (Criteria) this;
        }

        public Criteria andNovelContnetLessThan(String value) {
            addCriterion("NOVEL_CONTNET <", value, "novelContnet");
            return (Criteria) this;
        }

        public Criteria andNovelContnetLessThanOrEqualTo(String value) {
            addCriterion("NOVEL_CONTNET <=", value, "novelContnet");
            return (Criteria) this;
        }

        public Criteria andNovelContnetLike(String value) {
            addCriterion("NOVEL_CONTNET like", value, "novelContnet");
            return (Criteria) this;
        }

        public Criteria andNovelContnetNotLike(String value) {
            addCriterion("NOVEL_CONTNET not like", value, "novelContnet");
            return (Criteria) this;
        }

        public Criteria andNovelContnetIn(List<String> values) {
            addCriterion("NOVEL_CONTNET in", values, "novelContnet");
            return (Criteria) this;
        }

        public Criteria andNovelContnetNotIn(List<String> values) {
            addCriterion("NOVEL_CONTNET not in", values, "novelContnet");
            return (Criteria) this;
        }

        public Criteria andNovelContnetBetween(String value1, String value2) {
            addCriterion("NOVEL_CONTNET between", value1, value2, "novelContnet");
            return (Criteria) this;
        }

        public Criteria andNovelContnetNotBetween(String value1, String value2) {
            addCriterion("NOVEL_CONTNET not between", value1, value2, "novelContnet");
            return (Criteria) this;
        }

        public Criteria andText1IsNull() {
            addCriterion("TEXT1 is null");
            return (Criteria) this;
        }

        public Criteria andText1IsNotNull() {
            addCriterion("TEXT1 is not null");
            return (Criteria) this;
        }

        public Criteria andText1EqualTo(String value) {
            addCriterion("TEXT1 =", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1NotEqualTo(String value) {
            addCriterion("TEXT1 <>", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1GreaterThan(String value) {
            addCriterion("TEXT1 >", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1GreaterThanOrEqualTo(String value) {
            addCriterion("TEXT1 >=", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1LessThan(String value) {
            addCriterion("TEXT1 <", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1LessThanOrEqualTo(String value) {
            addCriterion("TEXT1 <=", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1Like(String value) {
            addCriterion("TEXT1 like", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1NotLike(String value) {
            addCriterion("TEXT1 not like", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1In(List<String> values) {
            addCriterion("TEXT1 in", values, "text1");
            return (Criteria) this;
        }

        public Criteria andText1NotIn(List<String> values) {
            addCriterion("TEXT1 not in", values, "text1");
            return (Criteria) this;
        }

        public Criteria andText1Between(String value1, String value2) {
            addCriterion("TEXT1 between", value1, value2, "text1");
            return (Criteria) this;
        }

        public Criteria andText1NotBetween(String value1, String value2) {
            addCriterion("TEXT1 not between", value1, value2, "text1");
            return (Criteria) this;
        }

        public Criteria andText2IsNull() {
            addCriterion("TEXT2 is null");
            return (Criteria) this;
        }

        public Criteria andText2IsNotNull() {
            addCriterion("TEXT2 is not null");
            return (Criteria) this;
        }

        public Criteria andText2EqualTo(String value) {
            addCriterion("TEXT2 =", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2NotEqualTo(String value) {
            addCriterion("TEXT2 <>", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2GreaterThan(String value) {
            addCriterion("TEXT2 >", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2GreaterThanOrEqualTo(String value) {
            addCriterion("TEXT2 >=", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2LessThan(String value) {
            addCriterion("TEXT2 <", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2LessThanOrEqualTo(String value) {
            addCriterion("TEXT2 <=", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2Like(String value) {
            addCriterion("TEXT2 like", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2NotLike(String value) {
            addCriterion("TEXT2 not like", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2In(List<String> values) {
            addCriterion("TEXT2 in", values, "text2");
            return (Criteria) this;
        }

        public Criteria andText2NotIn(List<String> values) {
            addCriterion("TEXT2 not in", values, "text2");
            return (Criteria) this;
        }

        public Criteria andText2Between(String value1, String value2) {
            addCriterion("TEXT2 between", value1, value2, "text2");
            return (Criteria) this;
        }

        public Criteria andText2NotBetween(String value1, String value2) {
            addCriterion("TEXT2 not between", value1, value2, "text2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table novel_content
     *
     * @mbg.generated do_not_delete_during_merge Sun Aug 07 22:00:12 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}