package com.yayanovel.entity;

public class Novel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.NOVEL_ID
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    private Long novelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.NOVEL_UID
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    private String novelUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.NOVEL_NAME
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    private String novelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.NOVEL_ADDR
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    private String novelAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.READ_NUM
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    private Long readNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.COLLECTION_NUM
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    private Long collectionNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.CATEGORY
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.IMG_ADDR
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    private String imgAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.IS_END
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    private String isEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.KEYWORDS
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.TEXT1
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    private String text1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.TEXT2
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    private String text2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.NOVEL_ID
     *
     * @return the value of novel.NOVEL_ID
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public Long getNovelId() {
        return novelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.NOVEL_ID
     *
     * @param novelId the value for novel.NOVEL_ID
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public void setNovelId(Long novelId) {
        this.novelId = novelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.NOVEL_UID
     *
     * @return the value of novel.NOVEL_UID
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public String getNovelUid() {
        return novelUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.NOVEL_UID
     *
     * @param novelUid the value for novel.NOVEL_UID
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public void setNovelUid(String novelUid) {
        this.novelUid = novelUid == null ? null : novelUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.NOVEL_NAME
     *
     * @return the value of novel.NOVEL_NAME
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public String getNovelName() {
        return novelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.NOVEL_NAME
     *
     * @param novelName the value for novel.NOVEL_NAME
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public void setNovelName(String novelName) {
        this.novelName = novelName == null ? null : novelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.NOVEL_ADDR
     *
     * @return the value of novel.NOVEL_ADDR
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public String getNovelAddr() {
        return novelAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.NOVEL_ADDR
     *
     * @param novelAddr the value for novel.NOVEL_ADDR
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public void setNovelAddr(String novelAddr) {
        this.novelAddr = novelAddr == null ? null : novelAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.READ_NUM
     *
     * @return the value of novel.READ_NUM
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public Long getReadNum() {
        return readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.READ_NUM
     *
     * @param readNum the value for novel.READ_NUM
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public void setReadNum(Long readNum) {
        this.readNum = readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.COLLECTION_NUM
     *
     * @return the value of novel.COLLECTION_NUM
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public Long getCollectionNum() {
        return collectionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.COLLECTION_NUM
     *
     * @param collectionNum the value for novel.COLLECTION_NUM
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public void setCollectionNum(Long collectionNum) {
        this.collectionNum = collectionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.CATEGORY
     *
     * @return the value of novel.CATEGORY
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.CATEGORY
     *
     * @param category the value for novel.CATEGORY
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.IMG_ADDR
     *
     * @return the value of novel.IMG_ADDR
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public String getImgAddr() {
        return imgAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.IMG_ADDR
     *
     * @param imgAddr the value for novel.IMG_ADDR
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public void setImgAddr(String imgAddr) {
        this.imgAddr = imgAddr == null ? null : imgAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.IS_END
     *
     * @return the value of novel.IS_END
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public String getIsEnd() {
        return isEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.IS_END
     *
     * @param isEnd the value for novel.IS_END
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public void setIsEnd(String isEnd) {
        this.isEnd = isEnd == null ? null : isEnd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.KEYWORDS
     *
     * @return the value of novel.KEYWORDS
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.KEYWORDS
     *
     * @param keywords the value for novel.KEYWORDS
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.TEXT1
     *
     * @return the value of novel.TEXT1
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public String getText1() {
        return text1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.TEXT1
     *
     * @param text1 the value for novel.TEXT1
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public void setText1(String text1) {
        this.text1 = text1 == null ? null : text1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.TEXT2
     *
     * @return the value of novel.TEXT2
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public String getText2() {
        return text2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.TEXT2
     *
     * @param text2 the value for novel.TEXT2
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    public void setText2(String text2) {
        this.text2 = text2 == null ? null : text2.trim();
    }
}