package com.yayanovel.entity;

public class NovelContent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel_content.NOVEL_CONTENT_ID
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    private Long novelContentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel_content.NOVEL_CONTENT_UID
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    private String novelContentUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel_content.NOVEL_UID
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    private String novelUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel_content.CHAPTER_UID
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    private String chapterUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel_content.NOVEL_NAME
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    private String novelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel_content.CHAPTER_NAME
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    private String chapterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel_content.NOVEL_CONTNET
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    private String novelContnet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel_content.TEXT1
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    private String text1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel_content.TEXT2
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    private String text2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel_content.NOVEL_CONTENT_ID
     *
     * @return the value of novel_content.NOVEL_CONTENT_ID
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public Long getNovelContentId() {
        return novelContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel_content.NOVEL_CONTENT_ID
     *
     * @param novelContentId the value for novel_content.NOVEL_CONTENT_ID
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public void setNovelContentId(Long novelContentId) {
        this.novelContentId = novelContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel_content.NOVEL_CONTENT_UID
     *
     * @return the value of novel_content.NOVEL_CONTENT_UID
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public String getNovelContentUid() {
        return novelContentUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel_content.NOVEL_CONTENT_UID
     *
     * @param novelContentUid the value for novel_content.NOVEL_CONTENT_UID
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public void setNovelContentUid(String novelContentUid) {
        this.novelContentUid = novelContentUid == null ? null : novelContentUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel_content.NOVEL_UID
     *
     * @return the value of novel_content.NOVEL_UID
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public String getNovelUid() {
        return novelUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel_content.NOVEL_UID
     *
     * @param novelUid the value for novel_content.NOVEL_UID
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public void setNovelUid(String novelUid) {
        this.novelUid = novelUid == null ? null : novelUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel_content.CHAPTER_UID
     *
     * @return the value of novel_content.CHAPTER_UID
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public String getChapterUid() {
        return chapterUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel_content.CHAPTER_UID
     *
     * @param chapterUid the value for novel_content.CHAPTER_UID
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public void setChapterUid(String chapterUid) {
        this.chapterUid = chapterUid == null ? null : chapterUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel_content.NOVEL_NAME
     *
     * @return the value of novel_content.NOVEL_NAME
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public String getNovelName() {
        return novelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel_content.NOVEL_NAME
     *
     * @param novelName the value for novel_content.NOVEL_NAME
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public void setNovelName(String novelName) {
        this.novelName = novelName == null ? null : novelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel_content.CHAPTER_NAME
     *
     * @return the value of novel_content.CHAPTER_NAME
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public String getChapterName() {
        return chapterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel_content.CHAPTER_NAME
     *
     * @param chapterName the value for novel_content.CHAPTER_NAME
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public void setChapterName(String chapterName) {
        this.chapterName = chapterName == null ? null : chapterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel_content.NOVEL_CONTNET
     *
     * @return the value of novel_content.NOVEL_CONTNET
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public String getNovelContnet() {
        return novelContnet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel_content.NOVEL_CONTNET
     *
     * @param novelContnet the value for novel_content.NOVEL_CONTNET
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public void setNovelContnet(String novelContnet) {
        this.novelContnet = novelContnet == null ? null : novelContnet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel_content.TEXT1
     *
     * @return the value of novel_content.TEXT1
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public String getText1() {
        return text1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel_content.TEXT1
     *
     * @param text1 the value for novel_content.TEXT1
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public void setText1(String text1) {
        this.text1 = text1 == null ? null : text1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel_content.TEXT2
     *
     * @return the value of novel_content.TEXT2
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public String getText2() {
        return text2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel_content.TEXT2
     *
     * @param text2 the value for novel_content.TEXT2
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    public void setText2(String text2) {
        this.text2 = text2 == null ? null : text2.trim();
    }
}