package com.yayanovel.entity;

public class ReadControl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read_control.READ_CONTROL_ID
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    private Long readControlId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read_control.READ_CONTROL_UID
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    private String readControlUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read_control.USER_UID
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    private String userUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read_control.NOVEL_UID
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    private String novelUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read_control.TEXT1
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    private String text1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read_control.TEXT2
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    private String text2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read_control.READ_CONTROL_ID
     *
     * @return the value of read_control.READ_CONTROL_ID
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    public Long getReadControlId() {
        return readControlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read_control.READ_CONTROL_ID
     *
     * @param readControlId the value for read_control.READ_CONTROL_ID
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    public void setReadControlId(Long readControlId) {
        this.readControlId = readControlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read_control.READ_CONTROL_UID
     *
     * @return the value of read_control.READ_CONTROL_UID
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    public String getReadControlUid() {
        return readControlUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read_control.READ_CONTROL_UID
     *
     * @param readControlUid the value for read_control.READ_CONTROL_UID
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    public void setReadControlUid(String readControlUid) {
        this.readControlUid = readControlUid == null ? null : readControlUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read_control.USER_UID
     *
     * @return the value of read_control.USER_UID
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    public String getUserUid() {
        return userUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read_control.USER_UID
     *
     * @param userUid the value for read_control.USER_UID
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    public void setUserUid(String userUid) {
        this.userUid = userUid == null ? null : userUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read_control.NOVEL_UID
     *
     * @return the value of read_control.NOVEL_UID
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    public String getNovelUid() {
        return novelUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read_control.NOVEL_UID
     *
     * @param novelUid the value for read_control.NOVEL_UID
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    public void setNovelUid(String novelUid) {
        this.novelUid = novelUid == null ? null : novelUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read_control.TEXT1
     *
     * @return the value of read_control.TEXT1
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    public String getText1() {
        return text1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read_control.TEXT1
     *
     * @param text1 the value for read_control.TEXT1
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    public void setText1(String text1) {
        this.text1 = text1 == null ? null : text1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read_control.TEXT2
     *
     * @return the value of read_control.TEXT2
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    public String getText2() {
        return text2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read_control.TEXT2
     *
     * @param text2 the value for read_control.TEXT2
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    public void setText2(String text2) {
        this.text2 = text2 == null ? null : text2.trim();
    }
}