package com.yayanovel.entity;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.USER_ID
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.USER_UID
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    private String userUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.USER_EMAIL
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.USER_PASSWORD
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.CREATE_TIME
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.UPDATE_TIME
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.TEXT1
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    private String text1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.TEXT2
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    private String text2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.USER_ID
     *
     * @return the value of user_info.USER_ID
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.USER_ID
     *
     * @param userId the value for user_info.USER_ID
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.USER_UID
     *
     * @return the value of user_info.USER_UID
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    public String getUserUid() {
        return userUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.USER_UID
     *
     * @param userUid the value for user_info.USER_UID
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    public void setUserUid(String userUid) {
        this.userUid = userUid == null ? null : userUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.USER_EMAIL
     *
     * @return the value of user_info.USER_EMAIL
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.USER_EMAIL
     *
     * @param userEmail the value for user_info.USER_EMAIL
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.USER_PASSWORD
     *
     * @return the value of user_info.USER_PASSWORD
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.USER_PASSWORD
     *
     * @param userPassword the value for user_info.USER_PASSWORD
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.CREATE_TIME
     *
     * @return the value of user_info.CREATE_TIME
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.CREATE_TIME
     *
     * @param createTime the value for user_info.CREATE_TIME
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.UPDATE_TIME
     *
     * @return the value of user_info.UPDATE_TIME
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.UPDATE_TIME
     *
     * @param updateTime the value for user_info.UPDATE_TIME
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.TEXT1
     *
     * @return the value of user_info.TEXT1
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    public String getText1() {
        return text1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.TEXT1
     *
     * @param text1 the value for user_info.TEXT1
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    public void setText1(String text1) {
        this.text1 = text1 == null ? null : text1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.TEXT2
     *
     * @return the value of user_info.TEXT2
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    public String getText2() {
        return text2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.TEXT2
     *
     * @param text2 the value for user_info.TEXT2
     *
     * @mbg.generated Sun Aug 29 22:58:45 CST 2021
     */
    public void setText2(String text2) {
        this.text2 = text2 == null ? null : text2.trim();
    }
}