package com.yayanovel.mapper;

import com.yayanovel.entity.Bookmark;
import com.yayanovel.entity.BookmarkExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface BookmarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Sun Aug 07 22:07:07 CST 2022
     */
    long countByExample(BookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Sun Aug 07 22:07:07 CST 2022
     */
    int deleteByExample(BookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Sun Aug 07 22:07:07 CST 2022
     */
    int deleteByPrimaryKey(Long bookmarkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Sun Aug 07 22:07:07 CST 2022
     */
    int insert(Bookmark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Sun Aug 07 22:07:07 CST 2022
     */
    int insertSelective(Bookmark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Sun Aug 07 22:07:07 CST 2022
     */
    List<Bookmark> selectByExample(BookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Sun Aug 07 22:07:07 CST 2022
     */
    Bookmark selectByPrimaryKey(Long bookmarkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Sun Aug 07 22:07:07 CST 2022
     */
    int updateByExampleSelective(@Param("record") Bookmark record, @Param("example") BookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Sun Aug 07 22:07:07 CST 2022
     */
    int updateByExample(@Param("record") Bookmark record, @Param("example") BookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Sun Aug 07 22:07:07 CST 2022
     */
    int updateByPrimaryKeySelective(Bookmark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Sun Aug 07 22:07:07 CST 2022
     */
    int updateByPrimaryKey(Bookmark record);
}