package com.yayanovel.mapper;

import com.yayanovel.entity.Bookmark;
import com.yayanovel.entity.BookmarkExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface BookmarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Thu Oct 07 14:37:34 CST 2021
     */
    long countByExample(BookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Thu Oct 07 14:37:34 CST 2021
     */
    int deleteByExample(BookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Thu Oct 07 14:37:34 CST 2021
     */
    int deleteByPrimaryKey(Long bookmarkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Thu Oct 07 14:37:34 CST 2021
     */
    int insert(Bookmark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Thu Oct 07 14:37:34 CST 2021
     */
    int insertSelective(Bookmark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Thu Oct 07 14:37:34 CST 2021
     */
    List<Bookmark> selectByExample(BookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Thu Oct 07 14:37:34 CST 2021
     */
    Bookmark selectByPrimaryKey(Long bookmarkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Thu Oct 07 14:37:34 CST 2021
     */
    int updateByExampleSelective(@Param("record") Bookmark record, @Param("example") BookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Thu Oct 07 14:37:34 CST 2021
     */
    int updateByExample(@Param("record") Bookmark record, @Param("example") BookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Thu Oct 07 14:37:34 CST 2021
     */
    int updateByPrimaryKeySelective(Bookmark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmark
     *
     * @mbg.generated Thu Oct 07 14:37:34 CST 2021
     */
    int updateByPrimaryKey(Bookmark record);

    /**
     * 根据用户uid查询书签
     * @param userUid
     * @return
     */
    List<Bookmark> getBookmarkByUserUid(@Param("userUid") String userUid);
}