package com.yayanovel.mapper;

import com.yayanovel.entity.Collection;
import com.yayanovel.entity.CollectionExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface CollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    long countByExample(CollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    int deleteByExample(CollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    int deleteByPrimaryKey(Long collectionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    int insert(Collection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    int insertSelective(Collection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    List<Collection> selectByExample(CollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    Collection selectByPrimaryKey(Long collectionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    int updateByExampleSelective(@Param("record") Collection record, @Param("example") CollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    int updateByExample(@Param("record") Collection record, @Param("example") CollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    int updateByPrimaryKeySelective(Collection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Thu Oct 07 10:04:31 CST 2021
     */
    int updateByPrimaryKey(Collection record);

    /**
     * 根据用户uid查询收藏表
     * @param userUid
     * @return
     */
    List<Collection> getCollectionByUserUid(@Param("userUid") String userUid);
}