package com.yayanovel.mapper;

import com.yayanovel.entity.NovelCategory;
import com.yayanovel.entity.NovelCategoryExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface NovelCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_category
     *
     * @mbg.generated Sun Aug 07 21:49:03 CST 2022
     */
    long countByExample(NovelCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_category
     *
     * @mbg.generated Sun Aug 07 21:49:03 CST 2022
     */
    int deleteByExample(NovelCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_category
     *
     * @mbg.generated Sun Aug 07 21:49:03 CST 2022
     */
    int deleteByPrimaryKey(Long categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_category
     *
     * @mbg.generated Sun Aug 07 21:49:03 CST 2022
     */
    int insert(NovelCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_category
     *
     * @mbg.generated Sun Aug 07 21:49:03 CST 2022
     */
    int insertSelective(NovelCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_category
     *
     * @mbg.generated Sun Aug 07 21:49:03 CST 2022
     */
    List<NovelCategory> selectByExample(NovelCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_category
     *
     * @mbg.generated Sun Aug 07 21:49:03 CST 2022
     */
    NovelCategory selectByPrimaryKey(Long categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_category
     *
     * @mbg.generated Sun Aug 07 21:49:03 CST 2022
     */
    int updateByExampleSelective(@Param("record") NovelCategory record, @Param("example") NovelCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_category
     *
     * @mbg.generated Sun Aug 07 21:49:03 CST 2022
     */
    int updateByExample(@Param("record") NovelCategory record, @Param("example") NovelCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_category
     *
     * @mbg.generated Sun Aug 07 21:49:03 CST 2022
     */
    int updateByPrimaryKeySelective(NovelCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_category
     *
     * @mbg.generated Sun Aug 07 21:49:03 CST 2022
     */
    int updateByPrimaryKey(NovelCategory record);

    /**
     * 查询类别
     * @return
     */
    List<NovelCategory> selectCatogary();
}