package com.yayanovel.mapper;

import com.yayanovel.entity.NovelContent;
import com.yayanovel.entity.NovelContentExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface NovelContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    long countByExample(NovelContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    int deleteByExample(NovelContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    int deleteByPrimaryKey(Long novelContentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    int insert(NovelContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    int insertSelective(NovelContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    List<NovelContent> selectByExample(NovelContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    NovelContent selectByPrimaryKey(Long novelContentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    int updateByExampleSelective(@Param("record") NovelContent record, @Param("example") NovelContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    int updateByExample(@Param("record") NovelContent record, @Param("example") NovelContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    int updateByPrimaryKeySelective(NovelContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_content
     *
     * @mbg.generated Sun Aug 07 22:00:12 CST 2022
     */
    int updateByPrimaryKey(NovelContent record);
}