package com.yayanovel.mapper;

import com.yayanovel.entity.Novel;
import com.yayanovel.entity.NovelExample;
import java.util.List;

import com.yayanovel.entity.UserInfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface NovelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    long countByExample(NovelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    int deleteByExample(NovelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    int deleteByPrimaryKey(Long novelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    int insert(Novel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    int insertSelective(Novel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    List<Novel> selectByExample(NovelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    Novel selectByPrimaryKey(Long novelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    int updateByExampleSelective(@Param("record") Novel record, @Param("example") NovelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    int updateByExample(@Param("record") Novel record, @Param("example") NovelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    int updateByPrimaryKeySelective(Novel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel
     *
     * @mbg.generated Sun Aug 29 22:58:10 CST 2021
     */
    int updateByPrimaryKey(Novel record);

    /**
     * 根据阅读量查询热门小说
     * @return
     */
    List<UserInfo> selectHotNovel();

    /**
     * 根据小说名字获取uuid
     * @param novelName
     * @return
     */
    Novel selectUuidByName(@Param("novelName") String novelName);
}