package com.yayanovel.mapper;

import com.yayanovel.entity.ReadControl;
import com.yayanovel.entity.ReadControlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReadControlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table read_control
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    long countByExample(ReadControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table read_control
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    int deleteByExample(ReadControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table read_control
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    int deleteByPrimaryKey(Long readControlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table read_control
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    int insert(ReadControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table read_control
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    int insertSelective(ReadControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table read_control
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    List<ReadControl> selectByExample(ReadControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table read_control
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    ReadControl selectByPrimaryKey(Long readControlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table read_control
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    int updateByExampleSelective(@Param("record") ReadControl record, @Param("example") ReadControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table read_control
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    int updateByExample(@Param("record") ReadControl record, @Param("example") ReadControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table read_control
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    int updateByPrimaryKeySelective(ReadControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table read_control
     *
     * @mbg.generated Sun Aug 29 22:58:28 CST 2021
     */
    int updateByPrimaryKey(ReadControl record);
}