package com.yayanovel.mapper;

import com.yayanovel.entity.UserInfo;
import com.yayanovel.entity.UserInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Aug 07 21:38:31 CST 2022
     */
    long countByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Aug 07 21:38:31 CST 2022
     */
    int deleteByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Aug 07 21:38:31 CST 2022
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Aug 07 21:38:31 CST 2022
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Aug 07 21:38:31 CST 2022
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Aug 07 21:38:31 CST 2022
     */
    List<UserInfo> selectByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Aug 07 21:38:31 CST 2022
     */
    UserInfo selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Aug 07 21:38:31 CST 2022
     */
    int updateByExampleSelective(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Aug 07 21:38:31 CST 2022
     */
    int updateByExample(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Aug 07 21:38:31 CST 2022
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Aug 07 21:38:31 CST 2022
     */
    int updateByPrimaryKey(UserInfo record);

    /**
     * 根据邮箱查询用户
     * @param userEmail
     * @return
     */
    UserInfo selectByEmail(String userEmail);

    /**
     * 根据userId查询用户
     * @param userUid
     * @return
     */
    UserInfo selectByUserUid(String userUid);

    /**
     * 根据用户信息更新用户表
     * @param userInfo
     */
    void updateAvtiveState(UserInfo userInfo);
    /**
     * 根据用户信息更新用户表
     * @param usrEmail
     */
    void updateActive(String usrEmail);

    /**
     * 修改用户密码
     * @param password
     * @param userEmail
     * @return
     */
    int updatePassword(String password, String userEmail);

}